name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'gh-pages'

jobs:
  build:
    uses: coditory/jvm-workflows/.github/workflows/build.yml@v1
    secrets: inherit
    with:
      snapshot: true
      snapshot-command: echo "Simulating snapshot publication %NEXT_VERSION%"
